### PR TITLE
[SEDONA-515] Add handling of noDataValues in RS_Resample

### LINKED ISSUE #1245: When I use Bicubic alg to resample a raster with no data pixel , the output raster would be filled unexpected data in no data pixel

### PR DESCRIPTION
**Pull request by prantogg**
## Did you read the Contributor Guide?

- Yes, I have read [Contributor Rules](https://sedona.apache.org/latest-snapshot/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/latest-snapshot/community/develop/)

## Is this PR related to a JIRA ticket?

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-515. The PR name follows the format `[SEDONA-XXX] my subject`.

## What changes were proposed in this PR?

Resolves #1245 .Adds handling of noDataValue for `bilinear` and `bicubic` algorithms of RS_Resample as follows.
- Extracts a noDataValue mask from the original raster.
- Replaces noDataValues in original raster with median of neighbors.
- Performs resampling on noDataValue mask and updated raster separately.
- To replant noDataValues - superimposes resampled noDataValue mask onto resampled raster

## How was this patch tested?

- Passes new and existing tests

## Did this PR include necessary documentation updates?

- No, this PR does not affect any public API so no need to change the docs.

### CODE REVIEW

File: common/src/test/java/org/apache/sedona/common/raster/RasterEditorsTest.java [hunk 1]
```diff
@@ -134,6 +134,61 @@ public void testResample() throws FactoryException, TransformException {
...
 
+    @Test
+    public void testResampleNoDataValueHandled() throws FactoryException, TransformException {
+        double[] values1 = {1,99,3,4,99,6,7,99,9,10,99,12};
+        double[] values2 = {10,11,-9999,13,14,15,-9999,17,18,19,-9999,21};
+        GridCoverage2D raster = RasterConstructors.makeEmptyRaster(1, "d", 4, 3, 0, 0, 2, -2, 0, 0, 0);
+        raster = MapAlgebra.addBandFromArray(raster, values1, 1, 99.0);
+        raster = MapAlgebra.addBandFromArray(raster, values2, 2, -9999.0);
+
+        GridCoverage2D newRaster = RasterEditors.resample(raster, 6, 5, 1, -1, false, "bilinear");
```
Comment (jiayuasu) [inline common/src/test/java/org/apache/sedona/common/raster/RasterEditorsTest.java:145]: Can you add a test to downsample the raster? E.g., the original raster is 4, 3, resample it to 2, 2?

**Review by jiayuasu — CHANGES_REQUESTED** [review]

**Review by jiayuasu — APPROVED** [review]
